### ISSUE TITLE
syntax error in the read me code 

### ISSUE THREAD

**Issue by myak2h** [andrewvy/chrome-remote-interface#31]
{:ok, pages} = ChromeRemoteInterface.Session.list_page(server) should be changed to {:ok, pages} = ChromeRemoteInterface.Session.list_pages(server)  i.e list_page to list_pages

**Comment by andrewvy** [comment]
Closed via https://github.com/andrewvy/chrome-remote-interface/pull/32, thanks @jackalcooper! :heart:
